name: CI Pipeline - Side Project
run-name: CI Pipeline triggered by ${{ github.actor }} on ${{ github.event_name }} event
on:
  push:
    branches-ignore:
      - "main"
      - "release"

jobs:
  RunTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install Pnpm
        run: npm install -g pnpm
      - name: install frontend dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Unit tests and Integration tests
        run: npm run test

      - name: Checker linter
        run: npm run lint

      - name: Change working directory
        run: cd src-tauri

      - name: Run Rust tests
        run: cargo test
